# application config
spring:
  # datasource
  datasource:
    hikari:
      connection-timeout: 200000
      maximum-pool-size: 10
    url: jdbc:postgresql://14.160.91.174:1632/ec_user
    username: postgres
    password: 'postgres'
  # spring jpa
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

# server config
server:
  port: 8210

# eureka client
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

# logging
logging:
  level:
    root: info
    com:
      vhc: debug
  file:
    name: './logs/ec-auth-srv.log'

# api versioning
vhc:
  ec:
    api:
      version:
        type: uri
        uri-location: begin
        uri-prefix: /api
    auth:
      customer:
        token-url: lb://ec-auth-srv/api/v1/token
        permit-urls:
          - /api/v1/auth
          - /api/v1/auth/**
          - /api/v1/token
    jwt:
      secrect_key_directory: D:\\vhc work\\econtract-service\\application\\ec-auth-srv\\src\\main\\resources\\rsa
      expires: 10080
    micro-services:
      api-url:
        customer: lb://ec-customer-srv/api/v1
        contract: lb://ec-contract-srv/api/v1
        admin: lb://ec-admin-srv/api/v1