spring:
  application:
    name: ec-bpmn-srv
  config:
    import: optional:configserver:http://localhost:8200
  cloud:
    config:
      uri: http://localhost:8200
      profile: dev
  profiles:
    active:
      - dev
      - prod
