spring:
  application:
    name: ec-config-srv
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:./ec-config

server:
  port: 8200

# eureka client
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
